apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service.fullname" . }}-configmap
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.properties: |
    {{- (tpl (.Files.Get "files/master.yaml") .) | nindent 4 }}
