apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service.fullname" . }}-configmap-backup
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- (tpl (.Files.Glob "flows/*").AsConfig .) | nindent 2 }}
