apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "service.fullname" . }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "service.name" . }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: liquidflow
        app: {{ template "service.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostname: {{ .Chart.Name }}
      subdomain: liquidflow-subdomain
      volumes:
        - configMap:
            name: config
          name: {{ template "service.fullname" . }}-configmap
        - configMap:
            name: flow
          name: {{ template "service.fullname" . }}-configmap-backup
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          env:
            - name:  EXECUTABLE
              value: "/app/flow"
            - name:  EXECUTABLE_ARG
              value: "/config/master.yml"
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /config
            - name: flow
              mountPath: /backup
          ports:
            - name: http
              containerPort: 9779
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /components
              port: http
          readinessProbe:
            httpGet:
              path: /components
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
