apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.fullname" . }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "service.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "service.fullname" . }}
subsets:
  - addresses:
      - ip: 192.0.2.43
    ports:
      - port: {{ .Values.service.port }}