apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-gogs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: .
    repoURL: https://gitea.com/gitea/helm-chart.git
    targetRevision: master
    helm:
      values: |
        dbType: sqllite
        config:
          secretKey: "secret key"
          disableInstaller: true
          offlineMode: false
          requireSignin: false
          disableRegistration: true


