apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.fullname" . }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9779
      targetPort: 9779
      protocol: TCP
      name: http
    - port: 7878
      targetPort: 7878
      protocol: TCP
      name: ws
  selector:
    app: {{ template "service.name" . }}
    release: {{ .Release.Name }}
